### ISSUE TITLE
Geez Numbers dataset 

### ISSUE THREAD

**Issue by hope-miky** [ethiopian/repos#14]
Hello! 

Here is a repository for a hand writing recognition system for Geez numbers in python.
link -  [https://github.com/Ethiopian-AI-Programmers/Geez-numbers-hand-writing-recognition-system](url) 

Thanks for creating this repository.
Tesfamichael Molla

**Comment by SamAsEnd** [comment]
Add the link to the readme file and send a pull request, shout out to @nathenapse

**Comment by desiyalew** [comment]
have u a dataset for geez numbers

**Comment by SamAsEnd** [comment]
Contact @Tesfamichael1074
