### ISSUE TITLE
more resources

### ISSUE THREAD

**Issue by adamsamson** [ethiopian/repos#3]
- Java input method editor for am_ET : https://github.com/menzew/input-method-editor-for-am_ET
- Amharic/Tigrinya/Oromo Dictionaries, Amharic-English parallel texts, magento and firefox Amharic translation : https://github.com/admasethiopia

**Comment by nathenapse** [comment]
I didn't add [Amharic-firefox-os](https://github.com/admasethiopia/firefox-os) because firefox-os has been discontinued.
